export default [
    {
        id:1,
        title:"个人中心",
        disabled:false,
        click:"personCenter"
    },
    {
        id:2,
        title:"设置",
        disabled:false,
        click:"setting"
    },
    {
        id:3,
        divider:true,
        title:"退出登录",
        disabled:false,
        click:"logOut"
    }
]